google.client.id=925934997768-p824rfigdrb4dmve5lo4erq37jlg7gk4.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:9999/ClothingShop/googleLogin
