google.client.id=619912310742-pb1m0qhr4g7e45hlnt396i766mrscuu1.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:9999/ClothingShop/googleLogin
